version: "3.9"

services:
  fake-news-app:
    build: .
    container_name: fake-news-app
    ports:
      - "8501:8501"
    env_file:
      - database/.env
      - rag_system/.env
    volumes:
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped
