version: "3.9"

services:
  fake-news-app:
    build: .
    container_name: fake-news-app
    ports:
      - "8501:8501"
    environment:
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_ENDPOINT=${AZURE_ENDPOINT}
      - AZURE_API_VERSION=${AZURE_API_VERSION}
    restart: unless-stopped
